### ISSUE TITLE
any plans for automatic encryption/description of git repository files

### ISSUE THREAD

**Issue by balupton** [fanf2/ssh-box#1]
Such that it functions akin to these:

- https://github.com/StackExchange/blackbox
- https://github.com/AGWA/git-crypt
- https://github.com/elasticdog/transcrypt
- https://github.com/jswidler/lockgit

As `ssh-box` uses ssh keys, it should be way easier and more automatic than all the above solutions.

**Comment by fanf2** [comment]
Heh, I wasn't expecting anyone to find this yet :-) perils of working in public :-)

I have a somewhat different point of view than the one embodied by the tools you listed. I have previously written about it at https://dotat.at/prog/regpg/doc/secrets.html (and there is a little more on the topic in https://dotat.at/prog/regpg/doc/rationale.html). I appreciate that I seem to be in the minority!

My reason for writing `ssh-box` is that I want a tool that uses modern crypto, in that it just uses `libsodium` (plus a little RSA support because `ssh-rsa` keys are so common); and which is much less obtuse and cluttered than `gpg`, so it is easier to wrap into higher-level applications. I hoped that [`age`][] would be that tool, but for usable safety I also need agent support, so that I can keep my private key encrypted but I don't need to keep typing the passphrase. And because `age` supports large files, it doesn't fix one of gpg's annoyances: they both can produce cleartext output before detecting a decryption failure.

[`age`]: https://github.com/FiloSottile/age

So the answer to your question is no, but it should be easier to make a transparent git encryption tool with `ssh-box` than with `gpg`.

And I will aim to make a tidy split between the core functionality and the command-line front-end, so that others can easily write their own CLI tools.

Thank you for taking an interest in what I am doing, and for asking an interesting question!
